### ISSUE TITLE
一个来自研究双臂协调运动规划学生的求助

### ISSUE THREAD

**Issue by hello-starry** [MingshanHe/Dual-Cooperator#1]
你好河明山：
       我是北京工业大学的一名硕士研究生，在无意之间发现了你关于双臂协调的github厂库，我目前研究的方向是双臂协调的运动规划，但是身边的同学们很少做这个方法的，我很渴望有人和我一起交流一些这方面的内容，如果你也是做这个方法的，我希望我们能成为朋友，一起和你探讨这方面的内容。

**Comment by MingshanHe** [comment]
非常感谢对我所作内容的关注，希望我的仓库对你有所帮助。欢迎交流，联系方式在我的主页上。
